### ISSUE TITLE
remove ls:report?

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/LevelSpace#126]
The only benefit to `ls:report` over `ls:of` is that it is a pre-fix reporter, thus allowing for the injection of arguments. Given that `ls:let` makes arguments unnecessary, and given that ls:report is not NetLogo'y, should it be retired?

**Comment by qiemem** [comment]
It's worth thinking about. I still use it for one-liners and it's *slightly* faster, but ya, definitely redundant...

Oh, actually the place it's slightly less redundant is, for instance:

```
let foo map [ i -> (ls:report my-model [ j -> do-stuff j ] i) ] range 10
```

Here, you can't use `ls:let` because `map` requires a reporter block. Alas, the age-old no-lets-in-reporters problem.

**Comment by arthurhjorth** [comment]
That answers that - we'll keep it. :)
